### ISSUE TITLE
External USB Storage Error

### ISSUE THREAD

**Issue by RyanWoirol** [magneticchen/Daijishou#162] opened 2022-12-30 19:58 UTC
I am trying to get my games to load from a USB flash drive.  They can be found, and they sync/scrape perfectly fine but when I try to play them I get "This item no longer exists. Please detach and resynchronize"

I can load them from their emulators though, just not through Daijisho.

**Comment by CoCoDaggorath** [comment] 2022-12-31 16:11
This issue is caused by Android 11, not a Daijshou bug.  Google implemented SD Card access restrictions for security in Android 11 so that apps can't see or access each other's data. This issue is also the root cause of Issue #159.  These Android 11 issues will affect any Android device running Android 11 and will eventually affect Retroid 2+ also once its OS is updated to Android 11.

This is a major issue that can be fixed by updating Daijshou so that it can ask for access and also allowing for manual path entry for games. Please see the following URLs for more information:
https://developer.android.com/about/versions/11/privacy/storage
https://developer.android.com/training/data-storage/manage-all-files

This is a fantastic frontend and would be my first choice on my Retroid 3, except for this issue.  Thank you for your hard work on this amazing frontend!

**Comment by antarusch** [comment] 2023-01-02 19:32
I´m having the same issue

**Comment by makigero** [comment] 2023-01-08 21:13
I am having a similar issue, but with the roms stored in a NAS.

**Comment by CrYoGeNiC6977** [comment] 2023-03-14 22:02
Will this compatibility be added in the future?  I know LaunchBox works with OTG drives.

**Comment by magneticchen** [comment] 2023-03-16 10:01
@CrYoGeNiC6977 Not currently planned.

**Comment by magneticchen** [comment] 2023-03-16 11:01
But I will try to make it accept uri formats for USBs.

**Comment by magneticchen** [comment] 2023-03-26 22:10
USB storage only supports Uri. And that is added in 1.4.

**Closed** 2023-03-26 22:10 UTC
Labels: enhancement, hanging
